name: Misspellings checks

# This workflow performs some misspelling checks on the repository

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  misspell:
    name: Check misspellings
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v4

    - name: Check misspellings
      uses: codespell-project/actions-codespell@v2
      with:
        builtin: clear,rare
        check_filenames: true
        skip: package-lock.json
