name: Publish Extension

# This workflow publish the extension when a new tag is pushed

on:
  push:
    tags:
      - '*'

jobs:
  check_changelog:
    name: Check changelog versions
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Clone
      uses: actions/checkout@v4

    - name: Get CHANGELOG version
      run: |
        echo "CHANGELOG_VERSION=$(grep -Po '(?<=## \[)(\d\.)+[^\]]' CHANGELOG.md | head -n 1)" >> "$GITHUB_ENV"

    - name: Check tag version against CHANGELOG version
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        if [ "${{ github.ref_name }}" != "${CHANGELOG_VERSION}" ]; then
            echo "Tag '${{ github.ref_name }}' and CHANGELOG '${CHANGELOG_VERSION}' versions mismatch!"
            exit 1
        fi

  publish:
    name: Publish the extension
    runs-on: ubuntu-latest
    needs: [check_changelog]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Clone
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: node

    - name: Packages installation
      run: npm install @vscode/vsce --save-dev

    - name: Publish to Visual Studio Marketplace
      run: npm run deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
